/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hms.enquiry.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.hms.enquiry.model.Enquiry;
import com.liferay.hms.enquiry.model.EnquiryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Enquiry service. Represents a row in the &quot;hms_Enquiry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EnquiryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnquiryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EnquiryImpl
 * @generated
 */
@JSON(strict = true)
public class EnquiryModelImpl
	extends BaseModelImpl<Enquiry> implements EnquiryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a enquiry model instance should use the <code>Enquiry</code> interface instead.
	 */
	public static final String TABLE_NAME = "hms_Enquiry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"enquiryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"mobileNo", Types.VARCHAR},
		{"concern", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("enquiryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobileNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("concern", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table hms_Enquiry (uuid_ VARCHAR(75) null,enquiryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,mobileNo VARCHAR(75) null,concern VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table hms_Enquiry";

	public static final String ORDER_BY_JPQL = " ORDER BY enquiry.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY hms_Enquiry.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOBILENO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EnquiryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _enquiryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEnquiryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _enquiryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Enquiry.class;
	}

	@Override
	public String getModelClassName() {
		return Enquiry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Enquiry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Enquiry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Enquiry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Enquiry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Enquiry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Enquiry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Enquiry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Enquiry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Enquiry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Enquiry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Enquiry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Enquiry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Enquiry, Object>>();
		Map<String, BiConsumer<Enquiry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Enquiry, ?>>();

		attributeGetterFunctions.put("uuid", Enquiry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Enquiry, String>)Enquiry::setUuid);
		attributeGetterFunctions.put("enquiryId", Enquiry::getEnquiryId);
		attributeSetterBiConsumers.put(
			"enquiryId", (BiConsumer<Enquiry, Long>)Enquiry::setEnquiryId);
		attributeGetterFunctions.put("groupId", Enquiry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Enquiry, Long>)Enquiry::setGroupId);
		attributeGetterFunctions.put("companyId", Enquiry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Enquiry, Long>)Enquiry::setCompanyId);
		attributeGetterFunctions.put("userId", Enquiry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Enquiry, Long>)Enquiry::setUserId);
		attributeGetterFunctions.put("userName", Enquiry::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Enquiry, String>)Enquiry::setUserName);
		attributeGetterFunctions.put("createDate", Enquiry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Enquiry, Date>)Enquiry::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Enquiry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Enquiry, Date>)Enquiry::setModifiedDate);
		attributeGetterFunctions.put("name", Enquiry::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Enquiry, String>)Enquiry::setName);
		attributeGetterFunctions.put("mobileNo", Enquiry::getMobileNo);
		attributeSetterBiConsumers.put(
			"mobileNo", (BiConsumer<Enquiry, String>)Enquiry::setMobileNo);
		attributeGetterFunctions.put("concern", Enquiry::getConcern);
		attributeSetterBiConsumers.put(
			"concern", (BiConsumer<Enquiry, String>)Enquiry::setConcern);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEnquiryId() {
		return _enquiryId;
	}

	@Override
	public void setEnquiryId(long enquiryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_enquiryId = enquiryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getMobileNo() {
		if (_mobileNo == null) {
			return "";
		}
		else {
			return _mobileNo;
		}
	}

	@Override
	public void setMobileNo(String mobileNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobileNo = mobileNo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalMobileNo() {
		return getColumnOriginalValue("mobileNo");
	}

	@JSON
	@Override
	public String getConcern() {
		if (_concern == null) {
			return "";
		}
		else {
			return _concern;
		}
	}

	@Override
	public void setConcern(String concern) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_concern = concern;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Enquiry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Enquiry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Enquiry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Enquiry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EnquiryImpl enquiryImpl = new EnquiryImpl();

		enquiryImpl.setUuid(getUuid());
		enquiryImpl.setEnquiryId(getEnquiryId());
		enquiryImpl.setGroupId(getGroupId());
		enquiryImpl.setCompanyId(getCompanyId());
		enquiryImpl.setUserId(getUserId());
		enquiryImpl.setUserName(getUserName());
		enquiryImpl.setCreateDate(getCreateDate());
		enquiryImpl.setModifiedDate(getModifiedDate());
		enquiryImpl.setName(getName());
		enquiryImpl.setMobileNo(getMobileNo());
		enquiryImpl.setConcern(getConcern());

		enquiryImpl.resetOriginalValues();

		return enquiryImpl;
	}

	@Override
	public Enquiry cloneWithOriginalValues() {
		EnquiryImpl enquiryImpl = new EnquiryImpl();

		enquiryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		enquiryImpl.setEnquiryId(
			this.<Long>getColumnOriginalValue("enquiryId"));
		enquiryImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		enquiryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		enquiryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		enquiryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		enquiryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		enquiryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		enquiryImpl.setName(this.<String>getColumnOriginalValue("name"));
		enquiryImpl.setMobileNo(
			this.<String>getColumnOriginalValue("mobileNo"));
		enquiryImpl.setConcern(this.<String>getColumnOriginalValue("concern"));

		return enquiryImpl;
	}

	@Override
	public int compareTo(Enquiry enquiry) {
		int value = 0;

		value = getName().compareTo(enquiry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Enquiry)) {
			return false;
		}

		Enquiry enquiry = (Enquiry)object;

		long primaryKey = enquiry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Enquiry> toCacheModel() {
		EnquiryCacheModel enquiryCacheModel = new EnquiryCacheModel();

		enquiryCacheModel.uuid = getUuid();

		String uuid = enquiryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			enquiryCacheModel.uuid = null;
		}

		enquiryCacheModel.enquiryId = getEnquiryId();

		enquiryCacheModel.groupId = getGroupId();

		enquiryCacheModel.companyId = getCompanyId();

		enquiryCacheModel.userId = getUserId();

		enquiryCacheModel.userName = getUserName();

		String userName = enquiryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			enquiryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			enquiryCacheModel.createDate = createDate.getTime();
		}
		else {
			enquiryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			enquiryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			enquiryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		enquiryCacheModel.name = getName();

		String name = enquiryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			enquiryCacheModel.name = null;
		}

		enquiryCacheModel.mobileNo = getMobileNo();

		String mobileNo = enquiryCacheModel.mobileNo;

		if ((mobileNo != null) && (mobileNo.length() == 0)) {
			enquiryCacheModel.mobileNo = null;
		}

		enquiryCacheModel.concern = getConcern();

		String concern = enquiryCacheModel.concern;

		if ((concern != null) && (concern.length() == 0)) {
			enquiryCacheModel.concern = null;
		}

		return enquiryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Enquiry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Enquiry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Enquiry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Enquiry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Enquiry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Enquiry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Enquiry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Enquiry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Enquiry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Enquiry.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _enquiryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _mobileNo;
	private String _concern;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Enquiry, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Enquiry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("enquiryId", _enquiryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("mobileNo", _mobileNo);
		_columnOriginalValues.put("concern", _concern);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("enquiryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("mobileNo", 512L);

		columnBitmasks.put("concern", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Enquiry _escapedModel;

}