/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hms.appointment.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.hms.appointment.model.Appointment;
import com.liferay.hms.appointment.model.AppointmentModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Appointment service. Represents a row in the &quot;hms_Appointment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppointmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppointmentImpl}.
 * </p>
 *
 * @author devendra
 * @see AppointmentImpl
 * @generated
 */
@JSON(strict = true)
public class AppointmentModelImpl
	extends BaseModelImpl<Appointment> implements AppointmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appointment model instance should use the <code>Appointment</code> interface instead.
	 */
	public static final String TABLE_NAME = "hms_Appointment";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"appointmentId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"mobile", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"country", Types.VARCHAR},
		{"age", Types.VARCHAR}, {"speciality", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appointmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobile", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("country", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("age", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("speciality", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table hms_Appointment (uuid_ VARCHAR(75) null,appointmentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,mobile VARCHAR(75) null,email VARCHAR(75) null,country VARCHAR(75) null,age VARCHAR(75) null,speciality VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table hms_Appointment";

	public static final String ORDER_BY_JPQL = " ORDER BY appointment.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY hms_Appointment.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COUNTRY_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppointmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appointmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppointmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appointmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Appointment.class;
	}

	@Override
	public String getModelClassName() {
		return Appointment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Appointment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appointment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Appointment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Appointment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Appointment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Appointment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Appointment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Appointment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Appointment, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Appointment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Appointment, Object>>();
		Map<String, BiConsumer<Appointment, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Appointment, ?>>();

		attributeGetterFunctions.put("uuid", Appointment::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Appointment, String>)Appointment::setUuid);
		attributeGetterFunctions.put(
			"appointmentId", Appointment::getAppointmentId);
		attributeSetterBiConsumers.put(
			"appointmentId",
			(BiConsumer<Appointment, Long>)Appointment::setAppointmentId);
		attributeGetterFunctions.put("groupId", Appointment::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Appointment, Long>)Appointment::setGroupId);
		attributeGetterFunctions.put("companyId", Appointment::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Appointment, Long>)Appointment::setCompanyId);
		attributeGetterFunctions.put("userId", Appointment::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Appointment, Long>)Appointment::setUserId);
		attributeGetterFunctions.put("userName", Appointment::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Appointment, String>)Appointment::setUserName);
		attributeGetterFunctions.put("createDate", Appointment::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Appointment, Date>)Appointment::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Appointment::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Appointment, Date>)Appointment::setModifiedDate);
		attributeGetterFunctions.put("name", Appointment::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Appointment, String>)Appointment::setName);
		attributeGetterFunctions.put("mobile", Appointment::getMobile);
		attributeSetterBiConsumers.put(
			"mobile", (BiConsumer<Appointment, String>)Appointment::setMobile);
		attributeGetterFunctions.put("email", Appointment::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Appointment, String>)Appointment::setEmail);
		attributeGetterFunctions.put("country", Appointment::getCountry);
		attributeSetterBiConsumers.put(
			"country",
			(BiConsumer<Appointment, String>)Appointment::setCountry);
		attributeGetterFunctions.put("age", Appointment::getAge);
		attributeSetterBiConsumers.put(
			"age", (BiConsumer<Appointment, String>)Appointment::setAge);
		attributeGetterFunctions.put("speciality", Appointment::getSpeciality);
		attributeSetterBiConsumers.put(
			"speciality",
			(BiConsumer<Appointment, String>)Appointment::setSpeciality);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAppointmentId() {
		return _appointmentId;
	}

	@Override
	public void setAppointmentId(long appointmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appointmentId = appointmentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getMobile() {
		if (_mobile == null) {
			return "";
		}
		else {
			return _mobile;
		}
	}

	@Override
	public void setMobile(String mobile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobile = mobile;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getCountry() {
		if (_country == null) {
			return "";
		}
		else {
			return _country;
		}
	}

	@Override
	public void setCountry(String country) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_country = country;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCountry() {
		return getColumnOriginalValue("country");
	}

	@JSON
	@Override
	public String getAge() {
		if (_age == null) {
			return "";
		}
		else {
			return _age;
		}
	}

	@Override
	public void setAge(String age) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_age = age;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAge() {
		return getColumnOriginalValue("age");
	}

	@JSON
	@Override
	public String getSpeciality() {
		if (_speciality == null) {
			return "";
		}
		else {
			return _speciality;
		}
	}

	@Override
	public void setSpeciality(String speciality) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_speciality = speciality;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Appointment.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Appointment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Appointment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Appointment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppointmentImpl appointmentImpl = new AppointmentImpl();

		appointmentImpl.setUuid(getUuid());
		appointmentImpl.setAppointmentId(getAppointmentId());
		appointmentImpl.setGroupId(getGroupId());
		appointmentImpl.setCompanyId(getCompanyId());
		appointmentImpl.setUserId(getUserId());
		appointmentImpl.setUserName(getUserName());
		appointmentImpl.setCreateDate(getCreateDate());
		appointmentImpl.setModifiedDate(getModifiedDate());
		appointmentImpl.setName(getName());
		appointmentImpl.setMobile(getMobile());
		appointmentImpl.setEmail(getEmail());
		appointmentImpl.setCountry(getCountry());
		appointmentImpl.setAge(getAge());
		appointmentImpl.setSpeciality(getSpeciality());

		appointmentImpl.resetOriginalValues();

		return appointmentImpl;
	}

	@Override
	public Appointment cloneWithOriginalValues() {
		AppointmentImpl appointmentImpl = new AppointmentImpl();

		appointmentImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		appointmentImpl.setAppointmentId(
			this.<Long>getColumnOriginalValue("appointmentId"));
		appointmentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appointmentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appointmentImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		appointmentImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		appointmentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appointmentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appointmentImpl.setName(this.<String>getColumnOriginalValue("name"));
		appointmentImpl.setMobile(
			this.<String>getColumnOriginalValue("mobile"));
		appointmentImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		appointmentImpl.setCountry(
			this.<String>getColumnOriginalValue("country"));
		appointmentImpl.setAge(this.<String>getColumnOriginalValue("age"));
		appointmentImpl.setSpeciality(
			this.<String>getColumnOriginalValue("speciality"));

		return appointmentImpl;
	}

	@Override
	public int compareTo(Appointment appointment) {
		int value = 0;

		value = getName().compareTo(appointment.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Appointment)) {
			return false;
		}

		Appointment appointment = (Appointment)object;

		long primaryKey = appointment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Appointment> toCacheModel() {
		AppointmentCacheModel appointmentCacheModel =
			new AppointmentCacheModel();

		appointmentCacheModel.uuid = getUuid();

		String uuid = appointmentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appointmentCacheModel.uuid = null;
		}

		appointmentCacheModel.appointmentId = getAppointmentId();

		appointmentCacheModel.groupId = getGroupId();

		appointmentCacheModel.companyId = getCompanyId();

		appointmentCacheModel.userId = getUserId();

		appointmentCacheModel.userName = getUserName();

		String userName = appointmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			appointmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			appointmentCacheModel.createDate = createDate.getTime();
		}
		else {
			appointmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appointmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appointmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appointmentCacheModel.name = getName();

		String name = appointmentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			appointmentCacheModel.name = null;
		}

		appointmentCacheModel.mobile = getMobile();

		String mobile = appointmentCacheModel.mobile;

		if ((mobile != null) && (mobile.length() == 0)) {
			appointmentCacheModel.mobile = null;
		}

		appointmentCacheModel.email = getEmail();

		String email = appointmentCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			appointmentCacheModel.email = null;
		}

		appointmentCacheModel.country = getCountry();

		String country = appointmentCacheModel.country;

		if ((country != null) && (country.length() == 0)) {
			appointmentCacheModel.country = null;
		}

		appointmentCacheModel.age = getAge();

		String age = appointmentCacheModel.age;

		if ((age != null) && (age.length() == 0)) {
			appointmentCacheModel.age = null;
		}

		appointmentCacheModel.speciality = getSpeciality();

		String speciality = appointmentCacheModel.speciality;

		if ((speciality != null) && (speciality.length() == 0)) {
			appointmentCacheModel.speciality = null;
		}

		return appointmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Appointment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appointment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Appointment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Appointment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Appointment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appointment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Appointment)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Appointment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Appointment.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _appointmentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _mobile;
	private String _email;
	private String _country;
	private String _age;
	private String _speciality;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Appointment, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Appointment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("appointmentId", _appointmentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("mobile", _mobile);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("country", _country);
		_columnOriginalValues.put("age", _age);
		_columnOriginalValues.put("speciality", _speciality);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("appointmentId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("mobile", 512L);

		columnBitmasks.put("email", 1024L);

		columnBitmasks.put("country", 2048L);

		columnBitmasks.put("age", 4096L);

		columnBitmasks.put("speciality", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Appointment _escapedModel;

}