/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hms.appointment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Appointment service. Represents a row in the &quot;hms_Appointment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.hms.appointment.model.impl.AppointmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.hms.appointment.model.impl.AppointmentImpl</code>.
 * </p>
 *
 * @author devendra
 * @see Appointment
 * @generated
 */
@ProviderType
public interface AppointmentModel
	extends BaseModel<Appointment>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appointment model instance should use the {@link Appointment} interface instead.
	 */

	/**
	 * Returns the primary key of this appointment.
	 *
	 * @return the primary key of this appointment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appointment.
	 *
	 * @param primaryKey the primary key of this appointment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this appointment.
	 *
	 * @return the uuid of this appointment
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this appointment.
	 *
	 * @param uuid the uuid of this appointment
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the appointment ID of this appointment.
	 *
	 * @return the appointment ID of this appointment
	 */
	public long getAppointmentId();

	/**
	 * Sets the appointment ID of this appointment.
	 *
	 * @param appointmentId the appointment ID of this appointment
	 */
	public void setAppointmentId(long appointmentId);

	/**
	 * Returns the group ID of this appointment.
	 *
	 * @return the group ID of this appointment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this appointment.
	 *
	 * @param groupId the group ID of this appointment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this appointment.
	 *
	 * @return the company ID of this appointment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appointment.
	 *
	 * @param companyId the company ID of this appointment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this appointment.
	 *
	 * @return the user ID of this appointment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this appointment.
	 *
	 * @param userId the user ID of this appointment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this appointment.
	 *
	 * @return the user uuid of this appointment
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this appointment.
	 *
	 * @param userUuid the user uuid of this appointment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this appointment.
	 *
	 * @return the user name of this appointment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this appointment.
	 *
	 * @param userName the user name of this appointment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this appointment.
	 *
	 * @return the create date of this appointment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this appointment.
	 *
	 * @param createDate the create date of this appointment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this appointment.
	 *
	 * @return the modified date of this appointment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appointment.
	 *
	 * @param modifiedDate the modified date of this appointment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this appointment.
	 *
	 * @return the name of this appointment
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this appointment.
	 *
	 * @param name the name of this appointment
	 */
	public void setName(String name);

	/**
	 * Returns the mobile of this appointment.
	 *
	 * @return the mobile of this appointment
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this appointment.
	 *
	 * @param mobile the mobile of this appointment
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the email of this appointment.
	 *
	 * @return the email of this appointment
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this appointment.
	 *
	 * @param email the email of this appointment
	 */
	public void setEmail(String email);

	/**
	 * Returns the country of this appointment.
	 *
	 * @return the country of this appointment
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this appointment.
	 *
	 * @param country the country of this appointment
	 */
	public void setCountry(String country);

	/**
	 * Returns the age of this appointment.
	 *
	 * @return the age of this appointment
	 */
	@AutoEscape
	public String getAge();

	/**
	 * Sets the age of this appointment.
	 *
	 * @param age the age of this appointment
	 */
	public void setAge(String age);

	/**
	 * Returns the speciality of this appointment.
	 *
	 * @return the speciality of this appointment
	 */
	@AutoEscape
	public String getSpeciality();

	/**
	 * Sets the speciality of this appointment.
	 *
	 * @param speciality the speciality of this appointment
	 */
	public void setSpeciality(String speciality);

	@Override
	public Appointment cloneWithOriginalValues();

}