/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hms.enquiry.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Enquiry service. Represents a row in the &quot;hms_Enquiry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.hms.enquiry.model.impl.EnquiryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.hms.enquiry.model.impl.EnquiryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Enquiry
 * @generated
 */
@ProviderType
public interface EnquiryModel
	extends BaseModel<Enquiry>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a enquiry model instance should use the {@link Enquiry} interface instead.
	 */

	/**
	 * Returns the primary key of this enquiry.
	 *
	 * @return the primary key of this enquiry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this enquiry.
	 *
	 * @param primaryKey the primary key of this enquiry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this enquiry.
	 *
	 * @return the uuid of this enquiry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this enquiry.
	 *
	 * @param uuid the uuid of this enquiry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the enquiry ID of this enquiry.
	 *
	 * @return the enquiry ID of this enquiry
	 */
	public long getEnquiryId();

	/**
	 * Sets the enquiry ID of this enquiry.
	 *
	 * @param enquiryId the enquiry ID of this enquiry
	 */
	public void setEnquiryId(long enquiryId);

	/**
	 * Returns the group ID of this enquiry.
	 *
	 * @return the group ID of this enquiry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this enquiry.
	 *
	 * @param groupId the group ID of this enquiry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this enquiry.
	 *
	 * @return the company ID of this enquiry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this enquiry.
	 *
	 * @param companyId the company ID of this enquiry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this enquiry.
	 *
	 * @return the user ID of this enquiry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this enquiry.
	 *
	 * @param userId the user ID of this enquiry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this enquiry.
	 *
	 * @return the user uuid of this enquiry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this enquiry.
	 *
	 * @param userUuid the user uuid of this enquiry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this enquiry.
	 *
	 * @return the user name of this enquiry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this enquiry.
	 *
	 * @param userName the user name of this enquiry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this enquiry.
	 *
	 * @return the create date of this enquiry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this enquiry.
	 *
	 * @param createDate the create date of this enquiry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this enquiry.
	 *
	 * @return the modified date of this enquiry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this enquiry.
	 *
	 * @param modifiedDate the modified date of this enquiry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this enquiry.
	 *
	 * @return the name of this enquiry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this enquiry.
	 *
	 * @param name the name of this enquiry
	 */
	public void setName(String name);

	/**
	 * Returns the mobile no of this enquiry.
	 *
	 * @return the mobile no of this enquiry
	 */
	@AutoEscape
	public String getMobileNo();

	/**
	 * Sets the mobile no of this enquiry.
	 *
	 * @param mobileNo the mobile no of this enquiry
	 */
	public void setMobileNo(String mobileNo);

	/**
	 * Returns the concern of this enquiry.
	 *
	 * @return the concern of this enquiry
	 */
	@AutoEscape
	public String getConcern();

	/**
	 * Sets the concern of this enquiry.
	 *
	 * @param concern the concern of this enquiry
	 */
	public void setConcern(String concern);

	@Override
	public Enquiry cloneWithOriginalValues();

}